### ISSUE TITLE
Menggunakan Versi Debounce yg Lebih Ringan

### ISSUE THREAD

**Issue by jefrydco** [febrihidayan/vuejs-webinar#1]
Hi Mas Febri, terima kasih telah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Febri.

Mas juga sudah menggunakan Vue CLI dan kerangka kerja CSS Bulma untuk aplikasi pencari teks pada video YouTube ini. Luar biasa Mas!

Saya ada 1 saran Mas untuk kode yg Mas kirim. Saran tersebut adalah menggunakan versi debounce yg lebih ringan. Pada berkas `src/App.vue` pada baris ke 58 Mas mengimpor paket NPM lodash secara langsung. Paket NPM Lodash merupakan paket yg berukuran cukup besar Mas jika di impor secara langsung. Mas dapat mengeceknya melalui tautan berikut, [BundlePhobia - Lodash](https://bundlephobia.com/result?p=lodash@4.17.19). Ukurannya sekitar 69Kb jika di minifikasi.

![BundlePhobia - Lodash](https://user-images.githubusercontent.com/20434351/89734459-5da83900-da86-11ea-86bf-f8b29f6c0941.png)

Mas dapat menggunakan paket NPM Lodash Debounce secara langsung yg bernama [Lodash Debounce](https://www.npmjs.com/package/lodash.debounce). Kemudian untuk mengimpor nya Mas dapat menambahkan awalan garis bawah (_) seperti halnya ketika Mas mengimpor Lodash secara keseluruhan. Kurang lebih seperti berikut contoh kodenya:

```javascript
import _debounce from 'lodash.debounce'
```

Semangat Mas! 😄

**Comment by febrihidayan** [comment]
Hahaha, saya lupa mas.
Biasanya saya membuatnya dengan cara 
`import { debounce } from 'lodash'` 👏👏

**Comment by jefrydco** [comment]
Siap Mas, saya akan membiarkan isu ini terbuka ya. Kalau nanti Mas ada waktu dan berkenan memperbaiki Mas bisa menutup isu ini. Terima kasih dan semangat selalu Mas! 😄

**Comment by febrihidayan** [comment]
close [6e1d8ce](https://github.com/febrihidayan/vuejs-webinar/commit/6e1d8cec4f19df955bc0a8edb8f46da38dc17c3c)
